source "https://rubygems.org"
gem "zurb-foundation", "3.2.5"
gem "compass"

# For more information on this file see:
# http://foundation.zurb.com/docs/sass.html
# http://zslabs.com/articles/versioned-dependencies-with-compass

